### ISSUE TITLE
ip parser only handles ipv4 addresses

### ISSUE THREAD

**Issue by chessai** [layer-3-communications/zeek-json#1]

**Comment by andrewthad** [comment]
This can be fixed since `ip` can now decode IPv6 addresses from `ShortText`.

**Comment by chessai** [comment]
ok

**Comment by andrewthad** [comment]
This has been fixed in 74d8b62ccf0b474d455f64cd004968feeecd5848. The other good news is that all the deps for this are now on hackage.
